name: wt1_wp1_036_bmi_hf_metabolomics
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  # basic
  - compilers
  # python
  - python=3.11
  - snakemake=9.1.9
  - graphviz=12.2.1
  - python-dotenv=1.1.0
  - pandoc
  - python-kaleido
  # r base and CRAN
  - r-base=4.4.3
  - r-gert
  - r-cairo
  - r-ncdf4
  - r-locfit
  # Bioconductor for MetaboAnalystR
  - bioconductor-biocparallel
  - bioconda::bioconductor-impute
  - bioconda::bioconductor-pcamethods
  - bioconda::bioconductor-globaltest
  - bioconda::bioconductor-globalancova
  - bioconda::bioconductor-rgraphviz
  - bioconda::bioconductor-preprocesscore
  - bioconda::bioconductor-genefilter
  - bioconda::bioconductor-sva
  - bioconda::bioconductor-limma
  - bioconda::bioconductor-kegggraph
  - bioconda::bioconductor-siggenes
  - bioconda::bioconductor-msnbase
  - bioconda::bioconductor-multtest
  - bioconda::bioconductor-rbgl
  - bioconda::bioconductor-edger
  - bioconda::bioconductor-fgsea
